package me.zed_0xff.zombie_buddy;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.invoke.VarHandle;

/** Runtime helpers for {@link me.zed_0xff.zombie_buddy.transformers.asmtree.ShadowRewrite} generated bytecode. */
public final class ShadowHandles {
    private ShadowHandles() {}

    public static VarHandle varHandle(String className, String fieldName, String fieldDesc) {
        return require(Reflect.on(className).getVarHandle(fieldDesc, fieldName), "VarHandle", className + "#" + fieldName + " " + fieldDesc);
    }

    public static MethodHandle methodHandle(String className, String methodName, String methodDesc) {
        return require(Reflect.on(className).getMethodHandle(methodDesc, methodName), "MethodHandle", className + "#" + methodName + methodDesc);
    }

    public static Object newInstance(String className) {
        Class<?> cls = require(Reflect.on(className).getType(), "class", className);

        try {
            MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(cls, MethodHandles.lookup());
            MethodHandle ctor = lookup.findConstructor(cls, MethodType.methodType(void.class));

            return ctor.invoke();
        } catch (Throwable t) {
            throw newExceptionInInitializer(t);
        }
    }

    private static <T> T require(T value, String kind, String what) {
        if (value == null) {
            throw new ExceptionInInitializerError(kind + " not found: " + what);
        }

        return value;
    }

    private static ExceptionInInitializerError newExceptionInInitializer(Throwable cause) {
        return new ExceptionInInitializerError(cause);
    }
}
